# Generated by Django 3.1.14 on 2022-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20221107_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
