# Generated by Django 3.1.14 on 2022-11-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohoraextra',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='registrohoraextra',
            name='pertence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
